format_version: 10
pipelines:
  gocd-server-config:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-0ca63c1:
        git: https://github.com/lavender2020/gocd-config-api.git
        username: lavender
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:F15dwgE7hOak1n8Hcm3oiiioeif
    stages:
    - config_gocd_server:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          gocd_server_api_config:
            timeout: 0
            elastic_profile_id: demo-app
            environment_variables:
              GOCD_DOMAIN: 10.205.21.149:31057
              PATTERN: '*.yaml'
              REPO_ID: gocd-server-config
              CONFIG_REPO_URL: https://github.com/lavender2020/gocd-config-api.git
            secure_variables:
              access_token: AES:bpsFl4mRA5XKonVZwsytyg==:EhUgoXY94GHc0wLXeKEXonZjiiid
            tasks:
            - exec:
                command: /bin/bash add-config-repo.sh $(GOCD_DOMAIN) $(access_token) $(REPO_ID) $(CONFIG_REPO_URL) $(PATTERN)
                run_if: passed
